Move all profiling dependencies to install_dependencies.sh (#22726)
### Ticket
N/A

### Problem description
Yesterday I tried to compile tt-metal with "--enable-profiler" and got
the following error:
```
../../../server/TracyWorker.cpp:24:10: fatal error: capstone.h: No such file or directory
   24 | #include <capstone.h>
```

I managed to fix that with `sudo apt install libcapstone-dev`

I managed to reproduce that on both ubuntu 24.04 and ubuntu 22.04

### What's changed
Add libcapstone-dev to build dependencies of tt-metal in
./install_dependencies.sh

### Checklist
- [ ] [All post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml)
CI passes
- [ ] [Blackhole Post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml)
CI with demo tests passes (if applicable)
- [ ] [Model
regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml)
CI passes (if applicable)
- [ ] [Device performance
regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml)
CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo
tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml)
CI passes (if applicable) See [recommended dev
flow](https://github.com/tenstorrent/tt-metal/blob/main/models/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] New/Existing tests provide coverage for changes