Revert rand changes to fix cmake generated unit tests (#24265)
### Ticket
Quick fix for rand function

### Problem description
function::rand function doesn't initialize tensors if type is not one of
the following : uint32_t, float, bfloat16
Fixing that issue lead to the error:

```
ttnn/CMakeFiles/ttnn.dir/Unity/unity_22_cxx.cxx.o.d -o ttnn/CMakeFiles/ttnn.dir/Unity/unity_22_cxx.cxx.o -c /work/build/ttnn/CMakeFiles/ttnn.dir/Unity/unity_22_cxx.cxx
In file included from /work/ttnn/cpp/ttnn/operations/creation.hpp:16,
                 from /work/ttnn/cpp/ttnn-pybind/operations/creation.cpp:18,
                 from /work/build/ttnn/CMakeFiles/ttnn.dir/Unity/unity_22_cxx.cxx:37:
/work/ttnn/cpp/ttnn/operations/functions.hpp: In function 'ttnn::Tensor ttnn::random::uniform(T, T, const tt::tt_metal::Shape&, tt::tt_metal::Layout)':
/work/ttnn/cpp/ttnn/operations/functions.hpp:475:23: error: static assertion failed: random::random(...) error: DataType not supported!
  475 |         static_assert(false, "random::random(...) error: DataType not supported!");
      |                       ^~~~~

```
It's unclear where the template is instantiated with a type that doesn't
meet the int/float requirements(can't build string with type name during
compile time). The issue can't be reproduced locally, and a text search
didn't help either.

To unblock the main branch, I’ve reverted my changes related to the rand
operation.


### What's changed
Reverted changes for random() function from function.hpp file

### Checklist
- [ ] [All post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml)
CI passes
- [ ] [Blackhole Post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml)
CI with demo tests passes (if applicable)
- [ ] [Model
regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml)
CI passes (if applicable)
- [ ] [Device performance
regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml)
CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo
tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml)
CI passes (if applicable) See [recommended dev
flow](https://github.com/tenstorrent/tt-metal/blob/main/models/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] New/Existing tests provide coverage for changes