#7921 lock_free_queue: Fix C++17 warnings around iterator
On newer GCC, the old iterator construct is deprecated, so switch to
implementing the right interface without inheritance.

For referenec, the error on Ubuntu LTS 24.04:

In file included from ./tt_metal/impl/dispatch/work_executor.hpp:14,
                 from ./tt_metal/impl/device/device.hpp:11,
                 from tt_metal/impl/device/device.cpp:5:
./tt_metal/impl/dispatch/lock_free_queue.hpp:64:38: error: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Werror=deprecated-declarations]
   64 |         class Iterator : public std::iterator<std::forward_iterator_tag, T> {
      |                                      ^~~~~~~~
In file included from /usr/include/c++/13/bits/stl_construct.h:61,
                 from /usr/include/c++/13/bits/stl_tempbuf.h:61,
                 from /usr/include/c++/13/memory:66,
                 from ./tt_metal/impl/device/device.hpp:7:
/usr/include/c++/13/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
In file included from ./tt_metal/impl/dispatch/work_executor.hpp:14,
                 from ./tt_metal/impl/device/device.hpp:11,
                 from ./tt_metal/impl/buffers/circular_buffer.hpp:10,
                 from ./tt_metal/impl/program/program.hpp:12,
                 from tt_metal/impl/program/program.cpp:5:

Signed-off-by: Olof Johansson <olofj@tenstorrent.com>