[TT-Transformers] Fix long context test cases with max_seq_len override (#34136)
### Ticket
Close https://github.com/tenstorrent/tt-metal/issues/33853

### Problem description
Summarized information from the issue:

Running `pytest models/tt_transformers/demo/simple_text_demo.py -k
"long-context" --max_seq_len=16384` incorrectly gives error:
```
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-64k] - AssertionError: Prompt prefill tokens (16384) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16384) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-32k] - AssertionError: Prompt prefill tokens (16384) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16384) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-performance-long-context-16k] - AssertionError: Prompt prefill tokens (16199) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16199) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-64k] - AssertionError: Prompt prefill tokens (16384) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16384) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-32k] - AssertionError: Prompt prefill tokens (16384) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16384) <= 16384
FAILED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-4-device_params0-accuracy-long-context-16k] - AssertionError: Prompt prefill tokens (16199) + maximum number of decoded iterations (200) needs to be <= than max_seq_len (16384)
assert (200 + 16199) <= 16384
```

The expected result is that the test clips the prompt sequence if its
length exceeds the `max_seq_len` passed on the command line (e.g.,
`16384` in the issue), reserves space for the to-be-generated tokens in
the total token budget (represented by `max_seq_len`), and then
successfully finish the text generation test.

This test failure can be seen on both WH and BH devices. 

### What's changed
This PR fix the bug that caused the above failed test cases by correctly
reserve space in the context for the generated tokens.

The bug is in the beginning of the `preprocess_inputs_prefill` function
in `models/tt_transformers/tt/common.py`:
- `max_prefill_len` is the override-able total token budget (i.e.,
`max_seq_len` as passed in from `simple_text_demo.py`)
- `max_context_len` is the model's maximum context length as specified
by the model creators (e.g, from HF's `config.json` of a model)
- `max_prefill_len <= max_context_len` must be true (there is actually
[a check for
this](https://github.com/tenstorrent/tt-metal/blob/81211c721c632c73592e085f1d9e2734c75a6052/models/tt_transformers/demo/simple_text_demo.py#L893-L896)
in `simple_text_demo.py`)
- Thus it is incorrect that the existing `if max_prefill_len >=
m_args.max_context_len:` prevents the reservation of space (through
`max_prefill_len -= max_generated_tokens`) for the generated tokens in
the `max_seq_len` token budget.

Using this fix, `pytest models/tt_transformers/demo/simple_text_demo.py
-k "long-context" --max_seq_len=16384` ran successfully with tests
running on IRD machines, e.g. with `mistralai/Mistral-7B-Instruct-v0.3`
on P150 machine:

- overly long input sequence is clipped correctly, leaving space for the
generated tokens (200 in length in this test case)
```bash
2025-12-10 07:26:46.277 | INFO     | models.tt_transformers.tt.common:preprocess_inputs_prefill:165 - Encoded prompt lengths:69164
2025-12-10 07:26:46.277 | INFO     | models.tt_transformers.tt.common:preprocess_inputs_prefill:173 - Left-clipping prompts to 16184
```

- all test cases are successful
```bash
================================================================= short test summary info ==================================================================
PASSED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-mesh_device0-device_params0-performance-long-context-64k]
PASSED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-mesh_device0-device_params0-performance-long-context-32k]
PASSED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-mesh_device0-device_params0-performance-long-context-16k]
PASSED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-mesh_device0-device_params0-accuracy-long-context-64k]
PASSED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-mesh_device0-device_params0-accuracy-long-context-32k]
PASSED models/tt_transformers/demo/simple_text_demo.py::test_demo_text[blackhole-mesh_device0-device_params0-accuracy-long-context-16k]
================================================= 6 passed, 34 deselected, 4 warnings in 851.45s (0:14:11) =================================================
2025-12-10 07:35:45.329 | info     |          Device | Closing user mode device drivers (tt_cluster.cpp:446)
```


### Checklist
**Tests to check regressions**
- [x] Black demo tests CI passes
- https://github.com/tenstorrent/tt-metal/actions/runs/20090540893 --
failed test cases not due to this PR
- [x] Single-card demo tests CI passes
- https://github.com/tenstorrent/tt-metal/actions/runs/20090561065 --
failed test cases not due to this PR
- [x] T3000 demo tests
- https://github.com/tenstorrent/tt-metal/actions/runs/20090576280 --
failed test cases not due to this PR

**Added new test case** to mistral CI to catch regression of `pytest
models/tt_transformers/demo/simple_text_demo.py -k "long-context"
--max_seq_len=16384` (we just need `"performance and long-context-16k"
-- max_seq_len=16384`)
- [x] https://github.com/tenstorrent/tt-metal/actions/runs/20091495905
-- saw "Left-clipping prompts to 16184" in [the log

](https://github.com/tenstorrent/tt-metal/actions/runs/20091495905/job/57640250312#step:7:6162)

**Before merging:**
- [x] revert ff200f1fa2d82899cb9b232371b7b1b8232db040
- through
[f4fe051](https://github.com/tenstorrent/tt-metal/pull/34136/commits/f4fe0511ed5becfb9f88dfe1d782d94fba5a5028)

**Test again after addressing review comments**
- [x] https://github.com/tenstorrent/tt-metal/actions/runs/20138158787

**Before merging**
- [x] revert bbe06896cb990b218924af7b6000e77313c01309
  - through 0c30227b9aee73cf6ec163fa5fd3eb2aebcdc011

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>