Enable -Wbool-operation (#21416)
### Ticket
N/A

### Problem description
-Wbool-operation has been disabled because we had a couple places in
code that get flagged.

```
error: bitwise negation of a boolean expression always evaluates to 'true'; did you mean logical negation? [-Werror,-Wbool-operation]
  244 |             TT_ASSERT(found_dispatch && ~found_dispatch_s);
      |                                         ^~~~~~~~~~~~~~~~~
      |                                         !
tt_metal/api/tt-metalium/assert.hpp:161:17: note: expanded from macro 'TT_ASSERT'
  161 |         if (not(condition)) [[unlikely]]                                                                    \
      |                 ^~~~~~~~~
```

### What's changed
Fixed the code
Enabled the warning