Revert "Replace truncating fp32->bf16 with tie-to-even rounding rule" (#26098)
Reverts tenstorrent/tt-metal#19882

Breaking apc ttnn group 7 with a pcc error:

https://github.com/tenstorrent/tt-metal/actions/runs/16662407209/job/47163100693#step:6:3576
```
tests/ttnn/unit_tests/operations/eltwise/test_composite.py::test_unary_logit[param=1.0-input_shapes=torch.Size([1, 1, 32, 32])] 2025-08-01 00:17:01.255 | warning  |          Always | Closing and re-initializing MetalContext with same parameters due to force_reinit flag. (metal_context.cpp:76)
2025-08-01 00:17:01.326 | info     |              Op | Where LLK - TST (where.cpp:123)
2025-08-01 00:17:01.327 | info     |              Op | Where LLK - TST (where.cpp:123)
2025-08-01 00:17:01.334 | info     |              Op | Where LLK - TST (where.cpp:123)
2025-08-01 00:17:01.334 | info     |              Op | Where LLK - TTT (where.cpp:90)
Error: test_unary_logit[param=1.0-input_shapes=torch.Size([1, 1, 32, 32])]

AssertionError: -1.0
FAILED
```