Make runtime_args_ptr const ref to solve clang-tidy error due to 779a2969b (#17364)
### Ticket
FYI @tt-rkim 
Related to @ayerofieiev-tt ticket
https://github.com/tenstorrent/tt-metal/issues/17208

Fixes clang-tidy

### Problem description
clang-tidy on CI
([link](https://github.com/tenstorrent/tt-metal/actions/runs/13039390588/job/36414797756))
failing wtih this error since commit
https://github.com/tenstorrent/tt-metal/commit/779a2969b310018fc57677ca34e883b4c365c69a

```
/home/ubuntu/actions-runner-2/_work/tt-metal/tt-metal/tt_metal/impl/dispatch/command_queue.cpp:469:34: error: the parameter 'runtime_args_ptr' is copied for each invocation but only used as a const reference; consider making it a const reference [performance-unnecessary-value-param,-warnings-as-errors]
  469 |     std::shared_ptr<RuntimeArgs> runtime_args_ptr,
      |                                  ^
      |     const                       &
200249 warnings generated.
Suppressed 200310 warnings (200248 in non-user code, 62 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
1 warning treated as error
```

### What's changed

- Make this argument const ref as suggested and kicked off code-analysis
job on this branch here:
https://github.com/tenstorrent/tt-metal/actions/runs/13053370584

### Checklist
- [ ] Code Analyis job previously failing
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] **(For models and ops writers)** Full [new
models](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml)
tests passes
- [ ] New/Existing tests provide coverage for changes