[Gemma3] Follow up prefetcher changes (#37853)
### Ticket
https://github.com/tenstorrent/tt-metal/issues/37774

### Problem description
[vLLM nightly
fail](https://github.com/tenstorrent/tt-metal/actions/runs/21983405660/job/63512204195#step:17:279)
:
```
RuntimeError: TT_FATAL @ /project/ttnn/cpp/ttnn/operations/experimental/transformer/rotary_embedding_llama/device/rotary_embedding_llama_device_operation.cpp:42: (cos.layout() == Layout::TILE)
```



### What's changed
- Use prefill rot mats in Gemma3 model
- Use memory_config in ScaledEmbedding as well
- Move to DRAM while untilizing, not in a separate call
- Turned off sampling on device in `text_demo.py` due to #32249

### Checklist

- [ ] [![vLLM nightly
tests](https://github.com/tenstorrent/tt-metal/actions/workflows/vllm-nightly-tests.yaml/badge.svg?branch=ppetrovic%2Fgemma3_rope)](https://github.com/tenstorrent/tt-metal/actions/runs/22316890990)
- [ ] [![(T3K) T3000 unit
tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml/badge.svg?branch=ppetrovic%2Fgemma3_rope)](https://github.com/tenstorrent/tt-metal/actions/runs/22314167642)
- [ ] [![(T3K) T3000 demo
tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml/badge.svg?branch=ppetrovic%2Fgemma3_rope)](https://github.com/tenstorrent/tt-metal/actions/runs/22352503361)

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>