Fix op device perf test in BH multi card pipelines (#38361)
### Ticket
NA

### Problem description
BH op device perf tests failing with this signature:
```
AssertionError: Device data missing: Op 987136 not present in cpp_device_perf_report.csv for device 0 (trace_id=None)
```

### What's changed
- increase op count env var

### Checklist
- [x] [BH multi card
demo](https://github.com/tenstorrent/tt-metal/actions/runs/22321291505)