Make CI builds consistent with local builds (#23658)
### Ticket

### Problem description
Currently the builds on CI are inconsistent with local builds.
For example, recently all local builds with the recommended env setup
were failing (fixed
[here](https://github.com/tenstorrent/tt-metal/pull/23611)) with this
error:
```
tt-metal/tt_metal/common/executor.hpp:7:10: fatal error: 'taskflow/taskflow.hpp' file not found
    7 | #include <taskflow/taskflow.hpp>
```
However all CI builds and tests were passing.

This was caused by a missing dependency on Taskflow, however, the needed
headers were accidentally found on CI just because they were in system
include path.

This issue arises from a flag `--cpm-use-local-packages` turned on for
CI builds. This flag forces CPM to use locally installed packages
instead of downloading them from CPM resulting in the fundamental
divergence of builds. Those libraries are downloaded and built from
source manually in the corresponding Dockerfile. This creates an even
worse divergence with build inconsistencies. Just as an example,
Dockerfile builds boost library with g++, and the package downloaded
from CPM is built with the same compiler as metal (typically clang),
resulting in a guaranteed divergence of the binaries.

### What's changed
Removed `--cpm-use-local-packages` flag
Removed extra package installation for build docker container

### Checklist
- [ ] [All post commit CI
passes](https://github.com/tenstorrent/tt-metal/actions/runs/15711240987)
- [x] [The build failure reproduces on CI before the fix was
merged](https://github.com/tenstorrent/tt-metal/actions/runs/15709446620)
- [x] New/Existing tests provide coverage for changes