Fix narrowing conversion in metal header (#17890)
### Ticket
N/A

### Problem description
Compiling an external metal cpp program with `clang++-17` fails with the
following error

```
.../tt_metal/api/tt-metalium/dispatch_settings.hpp:82:59: error: non-constant-expression cannot be narrowed from type 'int' to 'uint32_t' (aka 'unsigned int') in initializer list [-Wc++11-narrowing]
   82 |                 DispatchSettingsContainerKey k{core_type, hw_cqs};
      |                                                           ^~~~~~
```

### What's changed
Changed the loop variable to be u32, also removed one unused header.

### Checklist
- [ ] [All post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml)
CI passes

Signed-off-by: wenbinlyuTT <wenbinlyu@tenstorrent.com>