#5137: third_party/fmt: Temporary fixup for newer GCC
GCC thinks the local data_[] can be overrun, maybe because it assumes
last byte should be terminating NUL? Anyway, we should uprev the fmt
library to a newer version, but until then this will take care of the
warning.

tt_metal/third_party/fmt/fmt/core.h:1998:48: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
 1998 |     for (size_t i = 0; i < size; ++i) data_[i] = s[i];
      |                                       ~~~~~~~~~^~~~
tt_metal/third_party/fmt/fmt/core.h: In member function ‘constexpr decltype (ctx.begin()) fmt::v8::formatter<T, Char, typename std::enable_if<(fmt::v8::detail::type_constant<T, Char>::value != fmt::v8::detail::type::custom_type), void>::type>::parse(ParseContext&) [with ParseContext = fmt::v8::basic_format_parse_context<char>; T = fmt::v8::basic_string_view<char>; Char = char]’:
tt_metal/third_party/fmt/fmt/core.h:1990:8: note: at offset 4 into destination object ‘fmt::v8::detail::fill_t<char>::data_’ of size 4
 1990 |   Char data_[max_size] = {Char(' '), Char(0), Char(0), Char(0)};
      |        ^~~~~

Signed-off-by: Olof Johansson <olofj@tenstorrent.com>