Update triton to existing distributed whl version (#35882)
### Ticket
N/A

### Problem description
Run source tests/scripts/run_python_model_tests.sh
ERROR: Could not find a version that satisfies the requirement
triton==3.0.0 (from versions: 3.5.0, 3.5.1)
ERROR: No matching distribution found for triton==3.0.0

### What's changed
Triton updated to 3.5.1, which is a readily available wheel.

### Checklist
- [x] [(Galaxy) DeepSeek
tests](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-deepseek-tests.yaml)
https://github.com/tenstorrent/tt-metal/actions/runs/21016174936