bugprone-suspicious-stringview-data-usage (#27980)
### Ticket
#22758 
Closes #27981 

### Problem description
We have this check disabled:

https://clang.llvm.org/extra/clang-tidy/checks/bugprone/suspicious-stringview-data-usage.html

### What's changed
- Enable check
- Refactor some metal code to avoid string_view usage when there really
was no benefit
- Disable the check in `ttnn`, because there are too many violations to
ever fix in this lifetime.

```
/workspace/ttnn/cpp/ttnn/operations/eltwise/unary/unary_pybind.cpp:568:36: error: result of a `data()` call may not be null terminated, provide size information to the callee to prevent potential issues [bugprone-suspicious-stringview-data-usage,-warnings-as-errors]
  568 |             py::arg(parameter_name.data()) = parameter_default,
```

### Checklist
- [x] [All post
commit](https://github.com/tenstorrent/tt-metal/actions/runs/17479265455)
CI passes
- [x] New/Existing tests provide coverage for changes