[skip ci] #0: remove debug code from bmm reader (#34856)
### Ticket
Link to Github Issue N/A

### Problem description
Running matmul with watcher on resulted in an error:
```
/localdev/bbradel/tt-metal/ttnn/cpp/ttnn/operations/matmul/device/kernels/dataflow/reader_bmm_tile_layout_in1_sender_writer_padding.cpp:521:81: error: 'id' was not declared in this scope
  521 |                                         WATCHER_RING_BUFFER_PUSH(s.get_noc_addr(id, /*offset=*/0));
      |                                                                                 ^~
```

### What's changed
`id` should probably be `out_tensor_tile_id`. However, since this code
is no longer being debugged, this line is unnecessary and it's better to
remove this line.