fix: correct tt-metal build issue (#39)
There was a problem noticed in
https://github.com/tenstorrent/tt-llk/pull/22#issuecomment-2697911420
due to some build dependencies leaking out to tt-metal.
tt-llk still doesn't contain all dependencies needed for a standalone
build, so we had to copy some files over from tt-metal. They have been
placed in the hw_specific directory, but one of the files was missed and
stayed as part of llk common code, causing failures in tt-metal, due to
duplicate declarations:

```
In file included from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_heaviside.h:10,
                 from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/llk_math_eltwise_unary_sfpu_heaviside.h:9,
                 from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_math_unary_sfpu_api.h:12,
                 from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/include/compute_kernel_api.h:22,
                 from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tests/tt_metal/tt_metal/test_kernels/compute/eltwise_copy_3m.cpp:10,
                 from ../chlkc_math.cpp:3,
                 from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/hw/ckernels/wormhole_b0/metal/common/chlkc_list.h:21,
                 from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/hw/firmware/src/trisck.cc:14:
/home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_converter.h:10:7: error: redefinition of 'union ckernel::sfpu::Converter'
   10 | union Converter {
      |       ^~~~~~~~~
In file included from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/third_party/tt_llk/tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_relu.h:10,
                 from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/third_party/tt_llk/tt_llk_wormhole_b0/common/inc/ckernel_sfpu.h:36,
                 from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/third_party/tt_llk/tt_llk_wormhole_b0/common/inc/cmath_common.h:13,
                 from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_math_common_api.h:10,
                 from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/include/compute_kernel_api/common_globals.h:16,
                 from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/include/compute_kernel_api/common.h:7,
                 from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/include/compute_kernel_api/eltwise_binary.h:7,
                 from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tests/tt_metal/tt_metal/test_kernels/compute/eltwise_copy_3m.cpp:9:
/home/ubuntu/actions-runner/_work/tt-metal/tt-metal/tt_metal/third_party/tt_llk/tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_converter.h:10:7: note: previous definition of 'union ckernel::sfpu::Converter'
   10 | union Converter {
      |       ^~~~~~~~~
```


(https://github.com/tenstorrent/tt-metal/actions/runs/13655174698/job/38172822902)