fix: adjust const char* size checks using strlen for assertions (#34318)
### Ticket
None

### Problem description
File contains errors preventing it from compiling when the asserts are
turned on. This was never compiling, but it wasn't caught because no
checks were run.
```
/work/tests/tt_metal/tt_metal/test_kernels/misc/print_buffering.cpp: In function 'void kernel_main()':
/work/tests/tt_metal/tt_metal/test_kernels/misc/print_buffering.cpp:17:17: error: request for member 'size' in 'msg1', which is of non-class type 'const char*'
   17 |     ASSERT(msg1.size() + msg2.size() + msg3.size() > DPRINT_BUFFER_SIZE);
      |                 ^~~~
/work/tt_metal/hw/inc/debug/assert.h:58:15: note: in definition of macro 'ASSERT'
   58 |         if (!(condition))              \
      |               ^~~~~~~~~
/work/tests/tt_metal/tt_metal/test_kernels/misc/print_buffering.cpp:17:31: error: request for member 'size' in 'msg2', which is of non-class type 'const char*'
   17 |     ASSERT(msg1.size() + msg2.size() + msg3.size() > DPRINT_BUFFER_SIZE);
      |                               ^~~~
/work/tt_metal/hw/inc/debug/assert.h:58:15: note: in definition of macro 'ASSERT'
   58 |         if (!(condition))              \
      |               ^~~~~~~~~
/work/tests/tt_metal/tt_metal/test_kernels/misc/print_buffering.cpp:17:45: error: request for member 'size' in 'msg3', which is of non-class type 'const char*'
   17 |     ASSERT(msg1.size() + msg2.size() + msg3.size() > DPRINT_BUFFER_SIZE);
      |                                             ^~~~
/work/tt_metal/hw/inc/debug/assert.h:58:15: note: in definition of macro 'ASSERT'
   58 |         if (!(condition))              \
      |               ^~~~~~~~~
/work/tests/tt_metal/tt_metal/test_kernels/misc/print_buffering.cpp:29:22: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
   29 |     ASSERT(large_msg > DPRINT_BUFFER_SIZE);
```
See the full error log
[here](https://github.com/tenstorrent/tt-metal/actions/runs/20168258225/job/57897480697).

### What's changed
Fixed compilation errors where `.size()` was incorrectly called on
`const char*` pointers. Replaced with proper `strlen()` calls to get
string lengths.