#0: Don't fail generate-system-logs action (#21092)
### Ticket
None

### Problem description

Below error causes the action to fail.
```
dmesg: read kernel buffer failed: Operation not permitted
Error: Process completed with exit code 1.
```
This makes looking at failed jobs slightly annoying because the action
failure is the most recent error, and the log will open that step by
default instead of the test failure
E.g.
https://github.com/tenstorrent/tt-metal/actions/runs/14626776163/job/41047901224

Also seeing in newly provisioned machines running the containerized
flows:

https://github.com/tenstorrent/tt-metal/actions/runs/14627550388/job/41044407810#step:8:1
```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/ubuntu/actions-runner/_work/tt-metal/tt-metal/.github/actions/generate-system-logs'. Did you forget to run actions/checkout before running your local action?
```
This seems to imply the current method of running the action
inadvertently uses a (possibly stale) checked out copy on the
`action-runners` dir, and not the one checked out in the container.

### What's changed
Add `set +e` to ignore the system log commands if they fail and proceed
to the next command.
Use repo path to action due to running inside container.

### Checklist
- [ ] [All post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml)
CI passes
- [ ] [Blackhole Post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml)
CI with demo tests passes (if applicable)
- [ ] [Model
regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml)
CI passes (if applicable)
- [ ] [Device performance
regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml)
CI passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models
tests](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml)
CI passes (if applicable)
- [ ] New/Existing tests provide coverage for changes