Fix CI: Use Rustup to install newer Rust version fixing the build (#26756)
### Ticket

### Problem description
The build on CI is currently broken with the following error:
```
error: package `rayon-core v1.13.0` cannot be built because it requires rustc 1.80 or newer, while the currently active rustc version is 1.75.0
Either upgrade to rustc 1.80 or newer, or use
cargo update rayon-core@1.13.0 --precise ver
where `ver` is the latest version of `rayon-core` supporting rustc 1.75.0
```

### What's changed
Install the newer version of Rust in CI docker containers using Rustup
(the recommended method)
Updated tokenizers-cpp dependency to fix build issues

Future work is required to prevent this issue from happening in the
future and will be done in a separate (non urgent) PR

### Checklist
- [x] [All post commit CI build
passes](https://github.com/tenstorrent/tt-metal/actions/runs/16934398888)
- [x] New/Existing tests provide coverage for changes