Remove batched matmul from prefetcher unit tests (#36112)
### Ticket
Prefetcher unit tests were failing in upstream container because of this
error:
```
FAILED tests/ttnn/unit_tests/operations/transformers/test_prefetcher_TG.py::test_run_prefetcher_batched_weights[silicon_arch_name=wormhole_b0-device_params={'dispatch_core_axis': DispatchCoreAxis.COL, 'trace_region_size': 23887872}-2x2_grid-num_reader_cores=12-num_tensors=5-input_shapes=[(2048, 1280), (1280, 2048), (2048, 3584), (2048, 3584), (3584, 2048)]-dtypes=[DataType.BFLOAT8_B, DataType.BFLOAT8_B, DataType.BFLOAT4_B, DataType.BFLOAT4_B, DataType.BFLOAT8_B]-num_layers=80-batch_weights=True] - RuntimeError: TT_FATAL @ /project/ttnn/cpp/ttnn/operations/matmul/device/matmul_device_operation.cpp:121: optional_input_tensors.size() == 1
info:
Must have exactly 1 optional input tensor, got: 0
```

### Problem description
This is because the op batched weights matmul no longer expects multiple
in1 weights and doesnt seem to exist anymore, further more we do not run
the model with this setting so we just remove this codepath.
 
### What's changed
- remove usage of this op

### Checklist
- [ ] [Galaxy unit
tests](https://github.com/tenstorrent/tt-metal/actions/runs/21153459005)