Revert "Add uint32 support for binary shift ops" (#24083)
Reverts tenstorrent/tt-metal#23522

Breaking blackhole post-commit model unit tests:
```
FAILED models/demos/yolov4/tests/pcc/test_ttnn_yolov4_bh.py::test_yolov4[device_params0] - RuntimeError: TT_THROW @ /project/tt_metal/impl/program/program.cpp:134: tt::exception
info:
Failed to generate binaries for transpose_wh_rm TT_THROW @ /project/tt_metal/jit_build/build.cpp:66: tt::exception
info:
trisc2 build failed. Log: In file included from /work/.ttnn_runtime_artifacts/tt_metal/third_party/tt_llk/tt_llk_blackhole/llk_lib/llk_pack.h:625,
                 from /work/.ttnn_runtime_artifacts/tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_pack_api.h:16,
                 from /work/.ttnn_runtime_artifacts/tt_metal/include/compute_kernel_api/common_globals.h:24,
                 from /work/.ttnn_runtime_artifacts/tt_metal/include/compute_kernel_api/common.h:7,
                 from /work/.ttnn_runtime_artifacts/tt_metal/include/compute_kernel_api/eltwise_unary/eltwise_unary.h:7,
                 from /work/ttnn/cpp/ttnn/operations/data_movement/transpose/device/kernels/compute/transpose_wh_rm.cpp:7,
                 from ../chlkc_pack.cpp:3,
                 from /work/.ttnn_runtime_artifacts/tt_metal/hw/ckernels/blackhole/metal/common/chlkc_list.h:30,
                 from /work/.ttnn_runtime_artifacts/tt_metal/hw/firmware/src/trisck.cc:14:
/work/.ttnn_runtime_artifacts/tt_metal/third_party/tt_llk/tt_llk_blackhole/llk_lib/llk_pack_untilize.h: In instantiation of 'void _llk_pack_untilize_init_(uint32_t, uint32_t, uint32_t, uint32_t) [with long unsigned int block_ct_dim = 1; long unsigned int full_ct_dim = 1; bool diagonal = false; bool narrow_row = true; long unsigned int row_num_datums = 16; uint32_t = long unsigned int]':
/work/.ttnn_runtime_artifacts/tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_pack_api.h:217:94:   required from 'void llk_pack_untilize_init(uint32_t, uint32_t, uint32_t) [with long unsigned int block_ct_dim = 1; long unsigned int full_ct_dim = 1; bool diagonal = false; bool narrow_row = true; long unsigned int row_num_datums = 16; uint32_t = long unsigned int]'
/work/.ttnn_runtime_artifacts/tt_metal/include/compute_kernel_api/pack_untilize.h:77:5:   required from 'void ckernel::pack_untilize_dst_init_short(uint32_t, uint32_t, uint32_t) [with long unsigned int block_ct_dim = 1; long unsigned int full_ct_dim = 1; bool diagonal = false; bool narrow_row = true; long unsigned int row_num_datums = 16; uint32_t = long unsigned int]'
/work/ttnn/cpp/ttnn/operations/data_movement/transpose/device/kernels/compute/transpose_wh_rm.cpp:55:74:   required from 'void transpose_with_pack_untilize_narrow_row(uint32_t, uint32_t) [with long unsigned int Wt = 20; long unsigned int Ht = 1; long unsigned int HtWt = 20; bool use_narrow_row = true; long unsigned int row_size = 16; long unsigned int pack_num_pages_last_col = 1; long unsigned int pack_num_pages_last_row_col = 1; uint32_t = long unsigned int]'
/work/ttnn/cpp/ttnn/operations/data_movement/transpose/device/kernels/compute/transpose_wh_rm.cpp:171:49:   required from here
/work/.ttnn_runtime_artifacts/tt_metal/third_party/tt_llk/tt_llk_blackhole/llk_lib/llk_pack_untilize.h:143:38: error: static assertion failed: row_num_datums must be set to less than FACE_C_DIM for narrow_row packing
  143 |         static_assert(row_num_datums < FACE_C_DIM, "row_num_datums must be set to less than FACE_C_DIM for narrow_row packing");
      |                       ~~~~~~~~~~~~~~~^~~~~~~~~~~~
/work/.ttnn_runtime_artifacts/tt_metal/third_party/tt_llk/tt_llk_blackhole/llk_lib/llk_pack_untilize.h:143:38: note: the comparison reduces to '(16 < 16)'
```