[tt-train] Test only - Add INT8 as an unsupported type (#52761)
### PR Category
Test only

### Summary

https://github.com/tenstorrent/tt-metal/actions/runs/31158245558/job/92810410713
```
tt-train/tests/python/test_autograd.py:480: 
...
TypeError: [../tt-train/sources/ttml/nanobind/nb_util.cpp:57] nb::exception_type::type_error: (NB_THROW)Unsupported type: unknown
```

There was a recent commit
https://github.com/tenstorrent/tt-metal/commit/710bd295dd40e452f5796bd3f7ceab6996a6672a
that added support for `INT8` in metal. This cause the above failure.

Train doesn't support this currently, so this PR adds `INT8` to the
unsupported list.

Reproduce:
```
python -m pytest 'tt-train/tests/python/test_autograd.py::test_numpy_autograd_conversion[None-None-float32-tensor_data0]' -v
```

### CI Status
_Auto-generated on every push. Badges update live. Click a badge to
filter runs by this branch._

-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/sanity-tests.yaml/badge.svg?branch=ctr-kevinwu/int8-unsupported)](https://github.com/tenstorrent/tt-metal/actions/workflows/sanity-tests.yaml?query=branch:ctr-kevinwu/int8-unsupported)
-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/runtime-sanity-tests.yaml/badge.svg?branch=ctr-kevinwu/int8-unsupported)](https://github.com/tenstorrent/tt-metal/actions/workflows/runtime-sanity-tests.yaml?query=branch:ctr-kevinwu/int8-unsupported)
-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml/badge.svg?branch=ctr-kevinwu/int8-unsupported)](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:ctr-kevinwu/int8-unsupported)
-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/all-model-tests.yaml/badge.svg?branch=ctr-kevinwu/int8-unsupported)](https://github.com/tenstorrent/tt-metal/actions/workflows/all-model-tests.yaml?query=branch:ctr-kevinwu/int8-unsupported)
-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select.yaml/badge.svg?branch=ctr-kevinwu/int8-unsupported)](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select.yaml?query=branch:ctr-kevinwu/int8-unsupported)
-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-t3k.yaml/badge.svg?branch=ctr-kevinwu/int8-unsupported)](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-t3k.yaml?query=branch:ctr-kevinwu/int8-unsupported)
-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-galaxy.yaml/badge.svg?branch=ctr-kevinwu/int8-unsupported)](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-galaxy.yaml?query=branch:ctr-kevinwu/int8-unsupported)

Co-authored-by: Kevin Wu <ctr-kevinwu@tenstorrent.com>