#18887: Make smoke test report job name unique (#21923)
### Ticket
Fixes https://github.com/tenstorrent/tt-metal/issues/18887

### Problem description
Metalium smoke test report job names are not unique due to smoke tests
for a commit running on PR gate as well as APC, resulting in mutliple
smoke test report jobs with the same name present in the workflow run
E.g. two n150 smoke test reports

https://github.com/tenstorrent/tt-metal/actions/runs/14931406144/job/41958176255
(from PR gate)

https://github.com/tenstorrent/tt-metal/actions/runs/14931406144/job/41958176176
(from APC)

This causes a data pipeline validation error when pushing to superset

https://github.com/tenstorrent/tt-metal/actions/runs/14934367542/job/41958178433
```
Traceback (most recent call last):
  File "/home/runner/work/tt-metal/tt-metal/.github/scripts/data_analysis/create_pipeline_json.py", line 15, in <module>
    pipeline = create_cicd_json_for_data_analysis(
  File "/home/runner/work/tt-metal/tt-metal/infra/data_collection/cicd.py", line 98, in create_cicd_json_for_data_analysis
    pipeline = pydantic_models.Pipeline(
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Pipeline
  Value error, Duplicate job combination found: ('Metalium N150 smoke tests', datetime.datetime(2025, 5, 9, 17, 28, 8, tzinfo=TzInfo(UTC)), datetime.datetime(2025, 5, 9, 17, 28, 8, tzinfo=TzInfo(UTC)), datetime.datetime(2025, 5, 9, 17, 28, 8, tzinfo=TzInfo(UTC))) [type=value_error, input_value={'github_pipeline_id': 14..., tt_smi_version=None)]}, input_type=dict]
```

### What's changed
Add caller workflow name to the smoke test report job name (APC/PR/Merge
gate).
Remove deprecated/non-functional workaround from data pipeline script

### Checklist
- [x] APC:
https://github.com/tenstorrent/tt-metal/actions/runs/14936358032
(N300 smoke report with updated job name:
https://github.com/tenstorrent/tt-metal/actions/runs/14936358032/job/41966119289)