[skip ci] Produce data: Downgrade arch-label exception to warning (#21249)
### Ticket
None

### Problem description
T3k smoketest is running with `config-t3000` label.
The produce data workflow assumes that any job running with `config-*`
has an associated `arch-*` label, raising an exception otherwise.


https://github.com/tenstorrent/tt-metal/actions/runs/14672808714/job/41183054472
```
  File "/home/runner/work/tt-metal/tt-metal/infra/data_collection/github/utils.py", line 246, in get_job_row_from_github_job
    raise Exception(f"There must be an arch detected for config {detected_config}")
Exception: There must be an arch detected for config t3000
Error: Process completed with exit code 1.
```

### What's changed
Downgrade the exception to a warning. 
Assume config-t3000 label means wormhole cards.

### Checklist
- [x] New/Existing tests provide coverage for changes
Pipeline run on branch with fix:
https://github.com/tenstorrent/tt-metal/actions/runs/14673018956