Adjusting expected device perf for block_8x4_layer3_moe_fabric2d (#49071)
### Summary
This PR lowers the expected device-kernel duration for the
block_8x4_layer3_moe_fabric2d prefill perf test from 87_100_959 ns to
79_276_954 ns (±3% margin)


https://github.com/tenstorrent/tt-metal/actions/runs/28741662882/job/85226117759

> `2026-07-05 19:32:44.339 | INFO |
models.demos.deepseek_v3_d_p.utils.perf_utils:run_model_device_perf_test_with_merge:333
- InterleavedToShardedDeviceOperation 2,227 ns ( 2.2 us)
> 2026-07-05 19:32:44.339 | ERROR |
models.perf.device_perf_utils:check_device_perf:262 - AVG DEVICE KERNEL
DURATION [ns] 79276954.40625 is outside of expected range (84487930.23,
89713987.77)
> Error:
test_deepseek_v3_prefill_block_perf[block_8x4_layer3_moe_fabric2d]
> 
> AssertionError: Some performance metrics are outside of expected
range, see above for details.
> FAILED`
> 

### Checklist 
-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/demo-sp-release.yaml/badge.svg?branch=ddjekic/prefill_block_perf_adj)](https://github.com/tenstorrent/tt-metal/actions/workflows/demo-sp-release.yaml?query=branch:ddjekic/prefill_block_perf_adj)
Test unable to get a runner. Agreed with the team to proceed with merge
since it's a simple change

### CI Status
_Auto-generated on every push. Badges update live. Click a badge to
filter runs by this branch._

-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/sanity-tests.yaml/badge.svg?branch=ddjekic/prefill_block_perf_adj)](https://github.com/tenstorrent/tt-metal/actions/workflows/sanity-tests.yaml?query=branch:ddjekic/prefill_block_perf_adj)
-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/runtime-sanity-tests.yaml/badge.svg?branch=ddjekic/prefill_block_perf_adj)](https://github.com/tenstorrent/tt-metal/actions/workflows/runtime-sanity-tests.yaml?query=branch:ddjekic/prefill_block_perf_adj)
-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-sanity-tests.yaml/badge.svg?branch=ddjekic/prefill_block_perf_adj)](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-sanity-tests.yaml?query=branch:ddjekic/prefill_block_perf_adj)
-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml/badge.svg?branch=ddjekic/prefill_block_perf_adj)](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:ddjekic/prefill_block_perf_adj)
-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/all-model-tests.yaml/badge.svg?branch=ddjekic/prefill_block_perf_adj)](https://github.com/tenstorrent/tt-metal/actions/workflows/all-model-tests.yaml?query=branch:ddjekic/prefill_block_perf_adj)
-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select.yaml/badge.svg?branch=ddjekic/prefill_block_perf_adj)](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select.yaml?query=branch:ddjekic/prefill_block_perf_adj)
-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-t3k.yaml/badge.svg?branch=ddjekic/prefill_block_perf_adj)](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-t3k.yaml?query=branch:ddjekic/prefill_block_perf_adj)
-
[![](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-galaxy.yaml/badge.svg?branch=ddjekic/prefill_block_perf_adj)](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-galaxy.yaml?query=branch:ddjekic/prefill_block_perf_adj)