Revert "Demo bringup for yolov8x" (#21415)
Reverts tenstorrent/tt-metal#20501
Breaks post-commit models test
```
2025-04-30 01:43:00.638 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 6.14.0 (Device 0)
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.2.2, pluggy-1.5.0 -- /opt/venv/bin/python3
cachedir: .pytest_cache
rootdir: /work, configfile: pytest.ini
plugins: dash-2.15.0, split-0.8.2, github-actions-annotate-failures-0.3.0, timeout-2.2.0, anyio-4.9.0, xdist-3.6.1
timeout: 300.0s
timeout method: signal
timeout func_only: False
ERROR: not found: /work/tests/ttnn/integration_tests/yolov10/test_ttnn_yolov10.py::test_yolov10x
(no name '/work/tests/ttnn/integration_tests/yolov10/test_ttnn_yolov10.py::test_yolov10x' in any of [<Module tests/ttnn/integration_tests/yolov10/test_ttnn_yolov10.py>])
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
__ ERROR collecting tests/ttnn/integration_tests/yolov10/test_ttnn_yolov10.py __
ImportError while importing test module '/work/tests/ttnn/integration_tests/yolov10/test_ttnn_yolov10.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/venv/lib/python3.10/site-packages/_pytest/python.py:618: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
/opt/venv/lib/python3.10/site-packages/_pytest/pathlib.py:506: in import_path
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
/opt/venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:168: in exec_module
    exec(co, module.__dict__)
tests/ttnn/integration_tests/yolov10/test_ttnn_yolov10.py:11: in <module>
    from models.experimental.yolov10.tt.bottleneck import TtnnBottleNeck
models/experimental/yolov10/tt/bottleneck.py:6: in <module>
    from models.experimental.yolov10.tt.common import Conv
models/experimental/yolov10/tt/common.py:7: in <module>
    from models.experimental.yolo_common.yolo_utils import determine_num_cores, get_core_grid_from_num_cores
E   ModuleNotFoundError: No module named 'models.experimental.yolo_common'
- generated xml file: /work/generated/test_reports/most_recent_tests_20250430_014300.xml -
=========================== short test summary info ============================
ERROR tests/ttnn/integration_tests/yolov10/test_ttnn_yolov10.py
=============================== 1 error in 0.80s ====================
```