#19316: [skip ci] Read timestamps using fromisoformat() in produce_data workflow (#19319)
### Ticket
#19316

### Problem description
Fixes produce_data crash when the timestamp is missing fractional
seconds for some odd reason:

https://github.com/tenstorrent/tt-metal/actions/runs/13921485499/job/38975579816
```
2025-03-18 15:46:58.874 | INFO     | infra.data_collection.cicd:create_cicd_json_for_data_analysis:80 - Job id:38952637641 Analyzing test report /home/runner/work/tt-metal/tt-metal/generated/cicd/13918518051/artifacts/test_reports_03fea9c0-f115-4153-98c0-2416d5d741e1/most_recent_tests.xml
2025-03-18 15:46:58.906 | DEBUG    | infra.data_collection.junit_xml_utils:sanity_check_test_xml_:27 - Asserted pytest junit xml
2025-03-18 15:46:58.906 | INFO     | infra.data_collection.github.workflows:get_tests_from_test_report_path:301 - Found 1 testsuites
Traceback (most recent call last):
  File ".github/scripts/data_analysis/create_pipeline_json.py", line 15, in <module>
    pipeline = create_cicd_json_for_data_analysis(
  File "/home/runner/work/tt-metal/tt-metal/infra/data_collection/cicd.py", line 81, in create_cicd_json_for_data_analysis
    tests += get_tests_from_test_report_path(test_report_path)
  File "/home/runner/work/tt-metal/tt-metal/infra/data_collection/github/workflows.py", line 306, in get_tests_from_test_report_path
    default_timestamp = datetime.strptime(testsuite.attrib["timestamp"], "%Y-%m-%dT%H:%M:%S.%f")
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2025-03-18T08:36:31' does not match format '%Y-%m-%dT%H:%M:%S.%f'
```

### What's changed
Use `.fromisoformat()` to parse the timestamps instead of `.strptime()`
and providing our own time format specifier.

### Checklist
- [x] New/Existing tests provide coverage for changes
Pipeline rerun with branch:
https://github.com/tenstorrent/tt-metal/actions/runs/13933532743/job/38996270720