Bump UMD (#21471)
### Ticket
Link to Github Issue

### Problem description
Building umd tests fails with error due to
https://github.com/tenstorrent/tt-metal/commit/9a2a8e740dc5caf11343b9be9ee8cad348b817d0
which cleans up old GS code
```
CMake Error at tt_metal/third_party/umd/tests/CMakeLists.txt:47 (message):
  Failed to download
  https://raw.githubusercontent.com/tenstorrent/tt-metal/refs/heads/main/tt_metal/hw/inc/grayskull/noc/noc_parameters.h


-- Configuring incomplete, errors occurred!
Error: Process completed with exit code 1.
```

### What's changed
Bump UMD submodule to latest to pick up fix
https://github.com/tenstorrent/tt-umd/pull/817

### Checklist
- [x] [All post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml)
CI passes
https://github.com/tenstorrent/tt-metal/actions/runs/14760189576
- [x] [Blackhole Post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml)
CI passes
https://github.com/tenstorrent/tt-metal/actions/runs/14760191334