Revert "Remove cq id from TT-NN OPs 🐒 (#27635)" (#28477)
Change regressed the e2e perf for unet shallow and possibly other
models.

https://github.com/tenstorrent/tt-metal/actions/runs/17712179113/job/50332541416
AssertionError: Expected end-to-end performance to exceed 2646.00 fps
but was 1918.00 fps

Passing post commit

https://github.com/tenstorrent/tt-metal/actions/runs/17713661735/job/50336031965

---------

Co-authored-by: Pavle Josipovic <pjosipovic@tenstorrent.com>