#0: [skip ci] Add missing secrets:inherit to tg-quick-trigger.yaml (#19365)
### Ticket
Link to Github Issue

### Problem description
Failing tg-quick test doesn't send slack report:

https://github.com/tenstorrent/tt-metal/actions/runs/13951695608/job/39053215674#step:10:20
```
Error: Error: Need to provide at least one botToken or webhookUrl
```

### What's changed
Added `secrets: inherit` to tg-quick-trigger so that `slack_webhook_url:
${{ secrets.SLACK_WEBHOOK_URL }}` is available to the tg-quick slack
notification action.

### Checklist
- [ ] New/Existing tests provide coverage for changes