#28723: Fix Yolov11(n/m) Web Demo (#29028)
### Ticket
#28723 

### Problem description

Running web demo the python server could not load the model as it was
running out of L1 memory space.
See error message:
```
2025-09-19 15:50:00.836 | critical |          Always | Out of Memory: Not enough space to allocate 800 B L1_SMALL buffer across 50 banks, where each bank needs to store 16 B, but bank size is only 8000 B (assert.hpp:111)
ERROR:    Traceback (most recent call last):
  ...
  File "/app/tt-metal/./models/demos/yolov11m/web_demo/server/fast_api_yolov11.py", line 42, in startup
    model = YOLOv11PerformantRunner(device)
  File "/app/tt-metal/./models/demos/yolov11m/runner/performant_runner.py", line 51, in __init__
    self._capture_yolov11_trace_2cqs()
  File "/app/tt-metal/./models/demos/yolov11m/runner/performant_runner.py", line 62, in _capture_yolov11_trace_2cqs
    self.runner_infra.run()
  File "/app/tt-metal/./models/demos/yolov11m/runner/performant_runner_infra.py", line 110, in run
    self.output_tensor = self.ttnn_yolov11_model(self.input_tensor)
  File "/app/tt-metal/./models/demos/yolov11m/tt/ttnn_yolov11.py", line 115, in __call__
    x = self.detect(self.device, x16, x19, x22)
  File "/app/tt-metal/./models/demos/yolov11m/tt/ttnn_yolov11_detect.py", line 59, in __call__
    x4 = self.cv3_0_1_0(device, x4)
  File "/app/tt-metal/./models/demos/yolov11m/tt/common.py", line 231, in __call__
    x = self.conv(x)
  File "/app/tt-metal/./models/demos/yolov11m/tt/common.py", line 94, in __call__
    [x, [output_height, output_width], [self.weight, self.bias]] = ttnn.conv2d(
  File "/app/tt-metal/ttnn/ttnn/decorators.py", line 334, in __call__
    return self.function(*function_args, **function_kwargs)
RuntimeError: TT_THROW @ /app/tt-metal/tt_metal/impl/allocator/bank_manager.cpp:137: tt::exception
info:
Out of Memory: Not enough space to allocate 800 B L1_SMALL buffer across 50 banks, where each bank needs to store 16 B, but bank size is only 8000 B
backtrace:
```
Allocating a larger L1 buffer would result in this other error:
```
2025-09-19 15:05:34.959 | critical |          Always | Statically allocated circular buffers in program 139 clash with L1 buffers on core range [(x=0,y=0) - (x=7,y=6)]. L1 buffer allocated at 1136640 and static circular buffer region ends at 1136704 (assert.hpp:111)
ERROR:    Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 645, in lifespan
    async with self.lifespan_context(app):
  File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 540, in __aenter__
    await self._router.startup()
  File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 622, in startup
    await handler()
  File "/app/tt-metal/./models/demos/yolov11m/web_demo/server/fast_api_yolov11.py", line 41, in startup
    model = YOLOv11PerformantRunner(device)
  File "/app/tt-metal/./models/demos/yolov11m/runner/performant_runner.py", line 51, in __init__
    self._capture_yolov11_trace_2cqs()
  File "/app/tt-metal/./models/demos/yolov11m/runner/performant_runner.py", line 62, in _capture_yolov11_trace_2cqs
    self.runner_infra.run()
  File "/app/tt-metal/./models/demos/yolov11m/runner/performant_runner_infra.py", line 110, in run
    self.output_tensor = self.ttnn_yolov11_model(self.input_tensor)
  File "/app/tt-metal/./models/demos/yolov11m/tt/ttnn_yolov11.py", line 60, in __call__
    x = self.conv5(self.device, x)
  File "/app/tt-metal/./models/demos/yolov11m/tt/common.py", line 231, in __call__
    x = self.conv(x)
  File "/app/tt-metal/./models/demos/yolov11m/tt/common.py", line 94, in __call__
    [x, [output_height, output_width], [self.weight, self.bias]] = ttnn.conv2d(
  File "/app/tt-metal/ttnn/ttnn/decorators.py", line 334, in __call__
    return self.function(*function_args, **function_kwargs)
RuntimeError: TT_THROW @ /app/tt-metal/tt_metal/impl/program/program.cpp:912: tt::exception
info:
Statically allocated circular buffers in program 139 clash with L1 buffers on core range [(x=0,y=0) - (x=7,y=6)]. L1 buffer allocated at 1136640 and static circular buffer region ends at 1136704
backtrace:
```
### What's changed

Multiple different approaches have been tried to mitigate the issue:
 - changing L1 size
 - deallocating activations in the Detect Head portion of the model
 - re-organizing the Detect Head algorithm to release tensors early

And finally, @ssinghalTT suggested that if E2E tests worked, then it has
to be in the setup of the model within Fast API. Auditing the setup of
the model,
```
@app.on_event("startup")
async def startup():
    global model
    device_id = 0
    device = ttnn.CreateDevice(device_id, l1_small_size=YOLOV11_L1_SMALL_SIZE, trace_region_size=3211264, num_command_queues=2)
    device.enable_program_cache()
    model = YOLOv11PerformantRunner(device)
    model._capture_yolov11_trace_2cqs()
```
The items that jumped out were the `device.enable_program_cache()` and
`model._capture_yolov11_trace_2cqs()`.
Commenting out these lines allowed the web demo to work well.

TODO:
- [x] Apply the same fix to Yolov11 nano and fix it.

### Checklist
- [ ] [All post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml)
CI passes
- [ ] [Blackhole Post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml)
CI with demo tests passes (if applicable)
- [ ] [Model
regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml)
CI passes (if applicable)
- [ ] [Device performance
regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml)
CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo
tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml)
CI passes (if applicable) See [recommended dev
flow](https://github.com/tenstorrent/tt-metal/blob/main/models/docs/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] [Galaxy
quick](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-quick.yaml)
CI passes (if applicable)
- [ ] [Galaxy demo tests, for
Llama](https://github.com/tenstorrent/tt-metal/actions/workflows/galaxy-demo-tests.yaml)
CI passes, if applicable, because of current Llama work
- [ ] (For runtime and ops writers) [T3000 unit
tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml)
CI passes (if applicable, since this is run on push to main)
- [ ] (For models and ops writers) [T3000 demo
tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml)
CI passes (if applicable, since this is required for release)
- [ ] New/Existing tests provide coverage for changes