Fix T3K unit tests due to changed Attention class arguments + Disable qk fused ops for VL models (#35994)
### Ticket
Failures in T3K pipelines for Qwen25 VL with signature:
```
Cos and Sin are repeated for Q and K, so they must have the same batch size as the sum of Q and K batch sizes
```
and
```
TypeError: Attention.__init__() missing 1 required positional argument: 'state_dict'
```

### Problem description
In attention unit tests the model args was not passed to the Attention
class and the qwe25 vl demo has their own model args that did not
disable the qk fused flag

### What's changed
- pass model args back
- manually disable the qk fused flag in the qwen 25 demo

### Checklist
- [ ] [T3K unit
tests](https://github.com/tenstorrent/tt-metal/actions/runs/21076792351)
- [ ] [Single card demo for Qwen 25
VL](https://github.com/tenstorrent/tt-metal/actions/runs/21052126282)
- [ ] [T3K demo for Qwen25
VL](https://github.com/tenstorrent/tt-metal/actions/runs/21070397476)