Fix bug with --verbosity in tt-triage (#34871)
Using `--verbosity=x` didn't work because `console` was being created
after it and it was being used in `utils.VERBOSE()`...

Error output before:
```
> ./tools/tt-triage.py --verbosity=4
--------------------------  -----------------  --------------------------------------------------------------------------------------------------------------
tools/tt-triage.py:18       <module>           main()
tools/triage/triage.py:744  main                 args = parse_arguments(scripts)
tools/triage/triage.py:430  parse_arguments        process_arguments(arguments)
tools/triage/triage.py:375  process_arguments        utils.VERBOSE(f"Verbosity level: {utils.Verbosity.get().name} ({utils.Verbosity.get().value})")
tools/triage/utils.py:149   VERBOSE                    from triage import console
tools/triage/utils.py:149   VERBOSE            ImportError: cannot import name 'console' from 'triage' (/localdev/vjovanovic/tt-metal/tools/triage/triage.py)
--------------------------  -----------------  --------------------------------------------------------------------------------------------------------------
```