Remove legacy CCL sweep tests (#27607)
### Ticket
https://github.com/tenstorrent/tt-metal/issues/27521

### Problem description
the runner assigned to the ttnn-run-sweeps job in `ttnn-run-sweeps.yaml`
GitHub Action workflow is unable to generate sweeps for CCL. It just seg
faults.
```
 Run python3 tests/sweep_framework/sweeps_parameter_generator.py --module-name ccl.all_gather_n300 --dump-file --tag ci-main --explicit
  python3 tests/sweep_framework/sweeps_parameter_generator.py --module-name ccl.all_gather_n300 --dump-file --tag ci-main --explicit
  shell: bash --noprofile --norc -e -o pipefail {0}
2025-08-28 15:56:16.627 | INFO     | SWEEPS - Running current generation with tag: ci-main.
2025-08-28 15:56:16.627 | INFO     | SWEEPS - Generating test vectors for module ccl.all_gather_n300.
/__w/_temp/ba1abdfe-d911-46ca-a827-c13ee483890f.sh: line 1:   694 Segmentation fault      (core dumped) python3 tests/sweep_framework/sweeps_parameter_generator.py --module-name ccl.all_gather_n300 --dump-file --tag ci-main --explicit
Error: Process completed with exit code 139.
```
this is peculiar because it is capable of generating on a bh-36 ird
machine. For true comparison it would require testing on a wh machine
but nevertheless the sweep test causing these issues are no longer
applicable as the base ttnn api is no longer used.

### What's changed
Deleted CCL sweeps.
Updated workflow to disregard CCL exception
### Checklist
- [ ] [All post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml)
CI passes
- [ ] [Blackhole Post
commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml)
CI with demo tests passes (if applicable)
- [ ] [Model
regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml)
CI passes (if applicable)
- [ ] [Device performance
regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml)
CI passes (if applicable)
- [ ] (For models and ops writers) [Single-card demo
tests](https://github.com/tenstorrent/tt-metal/actions/workflows/single-card-demo-tests.yaml)
CI passes (if applicable) See [recommended dev
flow](https://github.com/tenstorrent/tt-metal/blob/main/models/docs/MODEL_ADD.md#a-recommended-dev-flow-on-github-for-adding-new-models).
- [ ] [Galaxy
quick](https://github.com/tenstorrent/tt-metal/actions/workflows/tg-quick-trigger.yaml)
CI passes (if applicable)
- [ ] [TG demo tests, for
Llama](https://github.com/tenstorrent/tt-metal/actions/workflows/tg-demo-tests.yaml)
CI passes, if applicable, because of current Llama work
- [ ] (For runtime and ops writers) [T3000 unit
tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-unit-tests.yaml)
CI passes (if applicable, since this is run on push to main)
- [ ] (For models and ops writers) [T3000 demo
tests](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml)
CI passes (if applicable, since this is required for release)
- [ ] New/Existing tests provide coverage for changes